import { Link } from 'react-router-dom';
import { Facebook, Instagram, Music2, MapPin, Phone, Mail, MessageCircle, ArrowUpRight } from 'lucide-react';
import { navItems, site } from '@/data/site';
import { createWhatsAppLink } from '@/utils/whatsapp';

export function Footer() {
  const message = 'Hello Edengrein Timber Supplies and Scaffolding, I would like to enquire about your products and services. Please share more information.';
  return <footer className="footer"><div className="container footer-main"><div className="footer-intro"><BrandMark /><p>{site.description}</p><a className="button button-light" href={createWhatsAppLink(message)} target="_blank" rel="noreferrer">Chat on WhatsApp <ArrowUpRight size={16} /></a></div><div className="footer-col"><h3>Explore</h3>{navItems.map((item) => <Link key={item.href} to={item.href}>{item.label}</Link>)}</div><div className="footer-col"><h3>Solutions</h3><Link to="/products#product-timber-mukima">Timber & Mukima</Link><Link to="/products#product-marine-boards">Construction Materials</Link><Link to="/services#service-scaffolding-hire">Scaffolding Hire</Link><Link to="/services#service-material-delivery">Material Delivery</Link><Link to="/services#service-scaffolding-maintenance-repairs">Maintenance & Repairs</Link></div><div className="footer-col footer-contact"><h3>Contact</h3>{site.phones.map((phone) => <a key={phone.href} href={phone.href}><Phone size={15} />{phone.label}</a>)}<a href={`mailto:${site.email}`}><Mail size={15} />{site.email}</a><a href={site.location.googleMapsUrl} target="_blank" rel="noreferrer"><MapPin size={15} />{site.location.address}</a><div className="socials"><a href={site.socials.facebook} target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={17} /></a><a href={site.socials.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17} /></a><a href={site.socials.tiktok} target="_blank" rel="noreferrer" aria-label="TikTok"><Music2 size={17} /></a><a href={createWhatsAppLink(message)} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={17} /></a></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Edengrein Timber Supplies and Scaffolding</span><span>Powered by <a href={site.credit} target="_blank" rel="noreferrer">Neonsol Creatives</a></span></div></footer>;
}

function BrandMark() { return <Link to="/" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="footer-brand"><img src="/images/Edengrein_Logo.jpeg" alt="Edengrein logo" onError={(event) => { event.currentTarget.style.display = 'none'; }} /><span><strong>Edengrein</strong><small>Timber Supplies & Scaffolding</small></span></Link>; }
